// <auto-generated />
using System;
using DerTransporte.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DerTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411030526_TravelScale")]
    partial class TravelScale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DerTransporte.Modules.AssignmentRole.Infrastructure.Entity.AssignmentRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("assignment_role", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.AuthCredentials.Infrastructure.Entity.AuthCredentialsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("auth_credentials", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.AuthSessions.Infrastructure.Entity.AuthSessionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Bids.Infrastructure.Entity.BidsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(19,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("EtaToPickup")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Point>("Coordinates")
                        .HasColumnType("point");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("StateorregionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StateorregionId");

                    b.ToTable("Citiesormunicipalities");
                });

            modelBuilder.Entity("DerTransporte.Modules.CompaniesStatus.Infrastructure.Entity.CompaniesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("companies_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.CompanyDocuments.Infrastructure.Entity.CompanyDocumentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("company_documents", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.CompanyVehicles.Infrastructure.Entity.CompanyVehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VehicleId");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Countries.Infrastructure.Entity.CountriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Isocode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Isocode")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DerTransporte.Modules.CreditWallet.Infrastructure.Entity.CreditWalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("DECIMAL(19,4)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("credit_wallet", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFrecuent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DisputesStatus.Infrastructure.Entity.DisputesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("disputes_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentCategory.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsCustomers.Infrastructure.Entity.DocumentsCustomersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("documents_customers", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsDrivers.Infrastructure.Entity.DocumentsDriversEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TypeDocumentId");

                    b.ToTable("documents_drivers", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsStatus.Infrastructure.Entity.DocumentsStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("documents_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsVehicles.Infrastructure.Entity.DocumentsVehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("DocumentStatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("DATE");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TypeDocumentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStatusId");

                    b.HasIndex("TypeDocumentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Drivers.Infrastructure.Entity.DriversEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadDetails.Infrastructure.Entity.LoadDetailsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<bool>("RequiredInsurance")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresPackaging")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("load_details", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadImages.Infrastructure.Entity.LoadImagesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("load_images", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadStatusHistory.Infrastructure.Entity.LoadStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LocationCoords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("load_status_history", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DestinationCoords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OfferedPrice")
                        .HasColumnType("DECIMAL(19,4)");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginCoords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeLoadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("VolumeM3")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<decimal>("WeightTons")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("TypeLoadId");

                    b.ToTable("loads", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.MessageType.Infrastructure.Entity.MessageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("message_type", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.NotificationType.Infrastructure.Entity.NotificationTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("notification_type", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.PaymentProviders.Infrastructure.Entity.PaymentProvidersEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("payment_providers", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.PaymentStatuses.Infrastructure.Entity.PaymentStatusesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("payment_statuses", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.PersonRoles.Infrastructure.Entity.PersonRolesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.ToTable("person_roles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.PersonStatus.Infrastructure.Entity.PersonStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("person_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.PersonTransport.Infrastructure.Entity.PersonTransportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RelationTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.HasIndex("RelationTypeId");

                    b.ToTable("person_transport", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PersonStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PersonStatusId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Plans.Infrastructure.Entity.PlansEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.ReasonDisputes.Infrastructure.Entity.ReasonDisputesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("reason_disputes", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.RelationType.Infrastructure.Entity.RelationTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("relation_type", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Roles.Infrastructure.Entity.RolesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Stateorregions.Infrastructure.Entity.StateorregionsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Stateorregions");
                });

            modelBuilder.Entity("DerTransporte.Modules.StatusBids.Infrastructure.Entity.StatusBidsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("status_bids", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.StatusChat.Infrastructure.Entity.StatusChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("status_chat", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.SubscriptionStatus.Infrastructure.Entity.SubscriptionStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subscription_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.SubscriptionType.Infrastructure.Entity.SubscriptionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subscription_type", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TransactionTypes.Infrastructure.Entity.TransactionTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("transaction_types", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanieName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LegalRepresentativeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ContactEmail")
                        .IsUnique();

                    b.HasIndex("LegalRepresentativeId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("transport_companies", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TravelScale.Infrastructure.Entity.TravelScaleEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("arrivalactual")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_actual");

                    b.Property<DateTime>("arrivalestimated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_estimated");

                    b.Property<Guid>("cityid")
                        .HasColumnType("char(36)")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("departureactual")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure_actual");

                    b.Property<short>("sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("tripid")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.HasIndex("cityid");

                    b.HasIndex("tripid");

                    b.ToTable("travel_scale", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Trips.Infrastructure.Entity.TripsEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("bidid")
                        .HasColumnType("char(36)")
                        .HasColumnName("bidid");

                    b.Property<Guid>("driverid")
                        .HasColumnType("char(36)")
                        .HasColumnName("driverid");

                    b.Property<DateTime?>("endtime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endtime");

                    b.Property<decimal>("finalprice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("finalprice");

                    b.Property<Guid>("loadid")
                        .HasColumnType("char(36)")
                        .HasColumnName("loadid");

                    b.Property<string>("manifestnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("manifestnumber");

                    b.Property<DateTime?>("starttime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starttime");

                    b.Property<string>("trackingtoken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trackingtoken");

                    b.HasKey("id");

                    b.HasIndex("bidid");

                    b.HasIndex("loadid");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("type_documents", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("type_load", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.TypeVehicles.Infrastructure.Entity.TypeVehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Axles")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CapacityM3")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TypeVehicleId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeVehicleId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.VehiculesStatus.Infrastructure.Entity.VehiculesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vehicules_status", (string)null);
                });

            modelBuilder.Entity("DerTransporte.Modules.AuthCredentials.Infrastructure.Entity.AuthCredentialsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DerTransporte.Modules.AuthSessions.Infrastructure.Entity.AuthSessionsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DerTransporte.Modules.Bids.Infrastructure.Entity.BidsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Stateorregions.Infrastructure.Entity.StateorregionsEntity", "Stateorregion")
                        .WithMany()
                        .HasForeignKey("StateorregionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stateorregion");
                });

            modelBuilder.Entity("DerTransporte.Modules.CompanyDocuments.Infrastructure.Entity.CompanyDocumentsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.DocumentsStatus.Infrastructure.Entity.DocumentsStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DocumentStatus");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("DerTransporte.Modules.CompanyVehicles.Infrastructure.Entity.CompanyVehiclesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DerTransporte.Modules.CreditWallet.Infrastructure.Entity.CreditWalletEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DerTransporte.Modules.Customers.Infrastructure.Entity.CustomersEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsCustomers.Infrastructure.Entity.DocumentsCustomersEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Customers.Infrastructure.Entity.CustomersEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.DocumentsStatus.Infrastructure.Entity.DocumentsStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DocumentStatus");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsDrivers.Infrastructure.Entity.DocumentsDriversEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.DocumentsStatus.Infrastructure.Entity.DocumentsStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Drivers.Infrastructure.Entity.DriversEntity", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentStatus");

                    b.Navigation("Driver");

                    b.Navigation("TypeDocument");
                });

            modelBuilder.Entity("DerTransporte.Modules.DocumentsVehicles.Infrastructure.Entity.DocumentsVehiclesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.DocumentsStatus.Infrastructure.Entity.DocumentsStatusEntity", "DocumentStatus")
                        .WithMany()
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", "TypeDocument")
                        .WithMany()
                        .HasForeignKey("TypeDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentStatus");

                    b.Navigation("TypeDocument");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DerTransporte.Modules.Drivers.Infrastructure.Entity.DriversEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadDetails.Infrastructure.Entity.LoadDetailsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadImages.Infrastructure.Entity.LoadImagesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("DerTransporte.Modules.LoadStatusHistory.Infrastructure.Entity.LoadStatusHistoryEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Customers.Infrastructure.Entity.CustomersEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", "TypeLoad")
                        .WithMany()
                        .HasForeignKey("TypeLoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");

                    b.Navigation("TypeLoad");
                });

            modelBuilder.Entity("DerTransporte.Modules.PersonRoles.Infrastructure.Entity.PersonRolesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DerTransporte.Modules.Roles.Infrastructure.Entity.RolesEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DerTransporte.Modules.PersonTransport.Infrastructure.Entity.PersonTransportEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.RelationType.Infrastructure.Entity.RelationTypeEntity", "RelationType")
                        .WithMany()
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Person");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.PersonStatus.Infrastructure.Entity.PersonStatusEntity", "PersonStatus")
                        .WithMany()
                        .HasForeignKey("PersonStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("PersonStatus");
                });

            modelBuilder.Entity("DerTransporte.Modules.Stateorregions.Infrastructure.Entity.StateorregionsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Countries.Infrastructure.Entity.CountriesEntity", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DerTransporte.Modules.TransportCompanies.Infrastructure.Entity.TransportCompaniesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "LegalRepresentative")
                        .WithMany()
                        .HasForeignKey("LegalRepresentativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.CompaniesStatus.Infrastructure.Entity.CompaniesStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("LegalRepresentative");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DerTransporte.Modules.TravelScale.Infrastructure.Entity.TravelScaleEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Citiesormunicipalities.Infrastructure.Entity.CitiesormunicipalitiesEntity", "City")
                        .WithMany()
                        .HasForeignKey("cityid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Trips.Infrastructure.Entity.TripsEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("tripid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DerTransporte.Modules.Trips.Infrastructure.Entity.TripsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Bids.Infrastructure.Entity.BidsEntity", "Bid")
                        .WithMany()
                        .HasForeignKey("bidid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.Loads.Infrastructure.Entity.LoadsEntity", "Load")
                        .WithMany()
                        .HasForeignKey("loadid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("Load");
                });

            modelBuilder.Entity("DerTransporte.Modules.TypeDocuments.Infrastructure.Entity.TypeDocumentsEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.DocumentCategory.Infrastructure.Entity.DocumentCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DerTransporte.Modules.Vehicles.Infrastructure.Entity.VehiclesEntity", b =>
                {
                    b.HasOne("DerTransporte.Modules.Persons.Infrastructure.Entity.PersonsEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.VehiculesStatus.Infrastructure.Entity.VehiculesStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DerTransporte.Modules.TypeVehicles.Infrastructure.Entity.TypeVehiclesEntity", "TypeVehicule")
                        .WithMany()
                        .HasForeignKey("TypeVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Status");

                    b.Navigation("TypeVehicule");
                });
#pragma warning restore 612, 618
        }
    }
}
